package markdown

import (
	"bytes"
	"html/template"
	"regexp"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/microcosm-cc/bluemonday"
	"github.com/yuin/goldmark"
	highlighting "github.com/yuin/goldmark-highlighting/v2"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/renderer/html"
	"github.com/yuin/goldmark/util"
)

// fenceDot returns the accent color for a code fence's language dot.
func fenceDot(lang string) string {
	switch strings.ToLower(lang) {
	case "shell", "sh", "bash", "zsh", "console":
		return "#7ee787"
	case "json":
		return "#79c0ff"
	default:
		return "#10b981"
	}
}

// codeBlockWrapper renders the Codex-style code block shell: a panel with a
// header bar (colored dot + language label) above the highlighted code.
// PreventSurroundingPre makes chroma emit only the token spans, so the
// <pre><code> pair written here is the one the CSS styles.
func codeBlockWrapper(w util.BufWriter, c highlighting.CodeBlockContext, entering bool) {
	if !entering {
		_, _ = w.WriteString("</code></pre>")
		return
	}
	lang := ""
	if l, ok := c.Language(); ok {
		lang = string(l)
	}
	_, _ = w.WriteString(`<pre class="codeblock">`)
	if lang != "" {
		_, _ = w.WriteString(`<span class="pre-head"><span class="fdot" style="background:` + fenceDot(lang) + `"></span>`)
		_, _ = w.WriteString(template.HTMLEscapeString(lang))
		_, _ = w.WriteString(`</span>`)
	}
	_, _ = w.WriteString("<code>")
}

var md = goldmark.New(
	goldmark.WithExtensions(
		extension.GFM,
		highlighting.NewHighlighting(
			highlighting.WithStyle("dracula"),
			highlighting.WithFormatOptions(
				chromahtml.WithLineNumbers(false),
				chromahtml.PreventSurroundingPre(true),
			),
			highlighting.WithWrapperRenderer(codeBlockWrapper),
		),
	),
	goldmark.WithRendererOptions(
		html.WithHardWraps(),
		html.WithXHTML(),
	),
)

var policy = func() *bluemonday.Policy {
	p := bluemonday.UGCPolicy()
	// Allow relative links generated by mention preprocessing.
	p.AllowAttrs("href").Matching(regexp.MustCompile(`^(/tickets/|/users/)`)).OnElements("a")
	// Allow inline styles produced by chroma syntax highlighting.
	p.AllowAttrs("style").OnElements("span", "pre", "code")
	p.AllowAttrs("class").OnElements("pre", "code")
	// Code block header bar (language label + colored dot).
	p.AllowAttrs("class").Matching(regexp.MustCompile(`^(pre-head|fdot)$`)).OnElements("span")
	// Allow task-list checkboxes (GFM extension renders these).
	p.AllowAttrs("type").Matching(regexp.MustCompile(`^checkbox$`)).OnElements("input")
	p.AllowAttrs("checked").OnElements("input")
	p.AllowAttrs("class").OnElements("input", "li")
	return p
}()

var (
	// #KEY-N preceded by start-of-line or whitespace/punctuation
	ticketMentionRe = regexp.MustCompile(`(^|[\s(,;:])#([A-Z]+-\d+)\b`)
	// @username preceded by start-of-line or whitespace/punctuation
	userMentionRe = regexp.MustCompile(`(^|[\s(,;:])@([a-zA-Z0-9_]+)\b`)
)

// preprocess converts @username and #KEY-N patterns to markdown links,
// skipping fenced code blocks.
func preprocess(src string) string {
	lines := strings.Split(src, "\n")
	inFence := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") {
			inFence = !inFence
		}
		if inFence {
			continue
		}
		line = ticketMentionRe.ReplaceAllString(line, "$1[#$2](/tickets/$2)")
		line = userMentionRe.ReplaceAllString(line, "$1[@$2](/users/$2)")
		lines[i] = line
	}
	return strings.Join(lines, "\n")
}

// Render converts Markdown source to sanitised HTML safe for use in templates.
func Render(src string) template.HTML {
	if src == "" {
		return ""
	}
	src = preprocess(src)
	var buf bytes.Buffer
	if err := md.Convert([]byte(src), &buf); err != nil {
		return template.HTML("")
	}
	safe := policy.SanitizeBytes(buf.Bytes())
	return template.HTML(safe)
}
