package markdown

import (
	"bytes"
	"html/template"
	"regexp"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/microcosm-cc/bluemonday"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	highlighting "github.com/yuin/goldmark-highlighting/v2"
	"github.com/yuin/goldmark/renderer/html"
)

var md = goldmark.New(
	goldmark.WithExtensions(
		extension.GFM,
		highlighting.NewHighlighting(
			highlighting.WithStyle("dracula"),
			highlighting.WithFormatOptions(
				chromahtml.WithLineNumbers(false),
			),
		),
	),
	goldmark.WithRendererOptions(
		html.WithHardWraps(),
		html.WithXHTML(),
	),
)

var policy = func() *bluemonday.Policy {
	p := bluemonday.UGCPolicy()
	// Allow relative links generated by mention preprocessing.
	p.AllowAttrs("href").Matching(regexp.MustCompile(`^(/tickets/|/users/)`)).OnElements("a")
	// Allow inline styles produced by chroma syntax highlighting.
	p.AllowAttrs("style").OnElements("span", "pre", "code")
	p.AllowAttrs("class").OnElements("pre", "code")
	return p
}()

var (
	// #KEY-N preceded by start-of-line or whitespace/punctuation
	ticketMentionRe = regexp.MustCompile(`(^|[\s(,;:])#([A-Z]+-\d+)\b`)
	// @username preceded by start-of-line or whitespace/punctuation
	userMentionRe = regexp.MustCompile(`(^|[\s(,;:])@([a-zA-Z0-9_]+)\b`)
)

// preprocess converts @username and #KEY-N patterns to markdown links,
// skipping fenced code blocks.
func preprocess(src string) string {
	lines := strings.Split(src, "\n")
	inFence := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") {
			inFence = !inFence
		}
		if inFence {
			continue
		}
		line = ticketMentionRe.ReplaceAllString(line, "$1[#$2](/tickets/$2)")
		line = userMentionRe.ReplaceAllString(line, "$1[@$2](/users/$2)")
		lines[i] = line
	}
	return strings.Join(lines, "\n")
}

// Render converts Markdown source to sanitised HTML safe for use in templates.
func Render(src string) template.HTML {
	if src == "" {
		return ""
	}
	src = preprocess(src)
	var buf bytes.Buffer
	if err := md.Convert([]byte(src), &buf); err != nil {
		return template.HTML("")
	}
	safe := policy.SanitizeBytes(buf.Bytes())
	return template.HTML(safe)
}
